Algoritmo "Antecessor"

Var

// Declaração de Variáveis //
val, ant: real

Inicio

// Apresentação e Definição de Variável pelo Usuário //
escreval("Visualizador de Antecessor")
escreval()
escreva("Digite um valor qualquer: ")
leia(val)

// Calculo do Antecessor //
ant <- val - 1

// Visualização do Resultado na Tela //
escreval("O Antecessor de", val, ", é:", ant)

Fimalgoritmo