Algoritmo "Área de Retângulo"
Var
// Declarações das variáveis
b, h, r: real

Inicio

// Apresentação e Definição do Valor das Variáveis
escreval("Área de Retângulo")
escreval()
escreva("Digite o Valor da Base: ")
leia(b)
escreval()
escreva("Digite o Valor da Altura: ")
leia(h)

// Calculo
r <- b * h

// Apresentação do Resultado ao Usuário
escreval()
escreva("Área de um Retângulo se calcula:", b, " .", h, " =", r)

Fimalgoritmo